// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-fatal warning emitted when an element cannot be fully processed.
 *
 * Warnings are structured so that callers can programmatically inspect
 * what was degraded during conversion.
 */
export type ConvertWarning = { "UnsupportedElement": { 
/**
 * Document format (e.g. "DOCX", "PPTX", "XLSX").
 */
format: string, 
/**
 * Name or description of the unsupported element.
 */
element: string, } } | { "PartialElement": { 
/**
 * Document format (e.g. "DOCX", "PPTX", "XLSX").
 */
format: string, 
/**
 * Name or description of the element.
 */
element: string, 
/**
 * Detail about what was degraded.
 */
detail: string, } } | { "FallbackUsed": { 
/**
 * Document format (e.g. "DOCX", "PPTX", "XLSX").
 */
format: string, 
/**
 * Original element type.
 */
from: string, 
/**
 * Fallback representation used.
 */
to: string, } } | { "ParseSkipped": { 
/**
 * Document format (e.g. "DOCX", "PPTX", "XLSX").
 */
format: string, 
/**
 * Reason the element was skipped.
 */
reason: string, } };
