// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaperSize } from "./PaperSize";
import type { PdfStandard } from "./PdfStandard";
import type { SlideRange } from "./SlideRange";

/**
 * Options controlling the conversion process.
 */
export type ConvertOptions = { 
/**
 * Filter XLSX sheets by name. Only sheets whose names are in this list
 * will be included. If `None`, all sheets are included.
 */
sheet_names: Array<string> | null, 
/**
 * Filter PPTX slides by range (1-indexed). If `None`, all slides are included.
 */
slide_range: SlideRange | null, 
/**
 * PDF standard to enforce. If `None`, produces a standard PDF 1.7.
 */
pdf_standard: PdfStandard | null, 
/**
 * Override paper size for the output PDF. If `None`, uses the source document's size.
 */
paper_size: PaperSize | null, 
/**
 * Additional font directories to search for fonts.
 */
font_paths: Array<string>, 
/**
 * Force landscape orientation. If `Some(true)`, swaps width/height so width > height.
 * If `Some(false)`, forces portrait. If `None`, uses source document orientation.
 */
landscape: boolean | null, 
/**
 * Enable tagged PDF output with document structure tags (H1-H6, P, Table, Figure).
 * When `true`, the output PDF includes accessibility tags that map document
 * structure for screen readers and assistive technologies.
 */
tagged: boolean, 
/**
 * Enable PDF/UA (Universal Accessibility) compliance. Implies `tagged: true`.
 * Combines tagged PDF with the PDF/UA-1 standard for full accessibility compliance.
 */
pdf_ua: boolean, };
