// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-stage timing and size metrics from a conversion.
 */
export type ConvertMetrics = { 
/**
 * Time spent parsing the input document (DOCX/PPTX/XLSX → IR).
 */
parse_duration: number, 
/**
 * Time spent generating Typst source code (IR → Typst).
 */
codegen_duration: number, 
/**
 * Time spent compiling Typst to PDF (Typst → PDF).
 */
compile_duration: number, 
/**
 * Total end-to-end conversion time.
 */
total_duration: number, 
/**
 * Size of the input file in bytes.
 */
input_size_bytes: bigint, 
/**
 * Size of the output PDF in bytes.
 */
output_size_bytes: bigint, 
/**
 * Number of pages in the output PDF.
 */
page_count: number, };
