// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper size for output PDF.
 */
export type PaperSize = "A4" | "Letter" | "Legal" | { "Custom": { width: number, height: number, } };
