// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range of slide numbers (1-indexed) for PPTX conversion.
 */
export type SlideRange = { 
/**
 * Start slide number (1-indexed, inclusive).
 */
start: number, 
/**
 * End slide number (1-indexed, inclusive).
 */
end: number, };
